//
// Created by polydome on 4/14/20.
//

#ifndef EKOSYSTEM_APPLICATIONEVENT_H
#define EKOSYSTEM_APPLICATIONEVENT_H

enum ApplicationEvent {
    TILE_SELECTED,
    ORGANISM_SELECTED,
    ORGANISM_CREATED
};

#endif //EKOSYSTEM_APPLICATIONEVENT_H
